DELIMITER $$
DROP TRIGGER IF EXISTS `OBATOUT_AFDELETE`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `OBATOUT_AFDELETE` AFTER DELETE ON `tobatout` FOR EACH ROW BEGIN
SET @KDOBAT=OLD.KDOBAT;
SET @QTY=OLD.QTY;
SET @ID=(SELECT id FROM tobatin WHERE kdobat=@KDOBAT AND keluar > 0 ORDER BY kdtrans  DESC LIMIT 1);
SET @KELUAR=(SELECT KELUAR FROM TOBATIN WHERE ID=@ID);
REPEAT
IF(@KELUAR > @QTY) THEN
UPDATE TOBATIN SET SISA=SISA+@QTY, KELUAR=KELUAR-@QTY WHERE ID=@ID;
SET @QTY=0;
END IF;
IF (@KELUAR < @QTY) THEN
UPDATE TOBATIN SET KELUAR=0, SISA=SISA+@KELUAR WHERE ID=@ID;
SET @QTY=@QTY-@KELUAR;
SET @ID=(SELECT ID FROM TOBATIN WHERE KDOBAT=@KDOBAT AND KELUAR > 0 ORDER BY KDTRANS  DESC LIMIT 1);
SET @KELUAR=(SELECT KELUAR FROM TOBATIN WHERE ID=@ID);
END IF;
IF(@KELUAR = @QTY) THEN
UPDATE TOBATIN SET KELUAR=0, SISA=SISA+@KELUAR WHERE ID=@ID;
SET @QTY=0;
END IF;
UNTIL @QTY=0
END REPEAT;
END;
$$

DROP TRIGGER IF EXISTS `OBATOUT_AFUPDATE`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `OBATOUT_AFUPDATE` AFTER UPDATE ON `tobatout` FOR EACH ROW BEGIN
SET @NQTY = NEW.QTY;
SET @KDOBAT = NEW.KDOBAT;
SET @OQTY = OLD.QTY;

IF (@NQTY < @OQTY) THEN
	SET @QTY = @OQTY - @NQTY;
	SET @ID=(SELECT ID FROM TOBATIN WHERE KDOBAT=@KDOBAT AND KELUAR > 0 ORDER BY KDTRANS  DESC LIMIT 1);
	SET @KELUAR=(SELECT KELUAR FROM TOBATIN WHERE ID=@ID);
	REPEAT
		IF(@KELUAR > @QTY) THEN
			UPDATE TOBATIN SET SISA=SISA+@QTY, KELUAR=KELUAR-@QTY WHERE ID=@ID;
			SET @QTY=0;
		END IF;
		IF (@KELUAR < @QTY) THEN
			UPDATE TOBATIN SET KELUAR=0, SISA=SISA+@KELUAR WHERE ID=@ID;
			SET @QTY=@QTY-@KELUAR;
			SET @ID=(SELECT ID FROM TOBATIN WHERE KDOBAT=@KDOBAT AND KELUAR > 0 ORDER BY KDTRANS  DESC LIMIT 1);
			SET @KELUAR=(SELECT KELUAR FROM TOBATIN WHERE ID=@ID);
		END IF;
		IF(@KELUAR = @QTY) THEN
			UPDATE TOBATIN SET KELUAR=0, SISA=SISA+@KELUAR WHERE ID=@ID;
			SET @QTY=0;
		END IF;
	UNTIL @QTY=0
	END REPEAT;
END IF;

IF (@NQTY > @OQTY) THEN
	SET @JKELUAR=@NQTY-@OQTY;
	SET @ID=(SELECT ID FROM TOBATIN WHERE KDOBAT=@KDOBAT AND SISA>0 ORDER BY KDTRANS  LIMIT 1);
	SET @SISA=(SELECT SISA FROM TOBATIN WHERE ID=@ID);
	REPEAT
		IF(@SISA>@JKELUAR) THEN
			UPDATE TOBATIN SET SISA=@SISA-@JKELUAR, KELUAR=KELUAR+@JKELUAR WHERE ID=@ID;
			SET @JKELUAR=0;
		END IF;
		IF (@SISA<@JKELUAR) THEN
			UPDATE TOBATIN SET SISA=0, KELUAR=KELUAR+@SISA WHERE ID=@ID;
			SET @JKELUAR=@JKELUAR-@SISA;
			SET @ID=(SELECT ID FROM TOBATIN WHERE KDOBAT=@KDOBAT AND SISA>0 ORDER BY KDTRANS LIMIT 1);
			SET @SISA=(SELECT SISA FROM TOBATIN WHERE ID=@ID);
		END IF;
		IF(@SISA=@JKELUAR) THEN
			UPDATE TOBATIN SET SISA=0,KELUAR=KELUAR+@JKELUAR WHERE ID=@ID;
			SET @JKELUAR=0;
		END IF;
	UNTIL @JKELUAR=0
	END REPEAT;
END IF;
END;
$$

DROP TRIGGER IF EXISTS `OBATOUT_AFINSERT`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `OBATOUT_AFINSERT` AFTER INSERT ON `tobatout` FOR EACH ROW BEGIN
SET @KODE=NEW.KDOBAT;
SET @JKELUAR=NEW.QTY;
SET @ID=(SELECT ID FROM TOBATIN WHERE KDOBAT=@KODE AND SISA>0 ORDER BY TGLTRANS  LIMIT 1);
SET @SISA=(SELECT SISA FROM TOBATIN WHERE ID=@ID);
REPEAT
IF(@SISA>@JKELUAR) THEN
UPDATE TOBATIN SET SISA=@SISA-@JKELUAR, KELUAR=KELUAR+@JKELUAR WHERE ID=@ID;
SET @JKELUAR=0;
END IF;
IF (@SISA<@JKELUAR) THEN
UPDATE TOBATIN SET SISA=0, KELUAR=KELUAR+@SISA WHERE ID=@ID;
SET @JKELUAR=@JKELUAR-@SISA;
SET @ID=(SELECT ID FROM TOBATIN WHERE KDOBAT=@KODE AND SISA>0 ORDER BY TGLTRANS LIMIT 1);
SET @SISA=(SELECT SISA FROM TOBATIN WHERE ID=@ID);
END IF;
IF(@SISA=@JKELUAR) THEN
UPDATE TOBATIN SET SISA=0,KELUAR=KELUAR+@JKELUAR WHERE ID=@ID;
SET @JKELUAR=0;
END IF;
UNTIL @JKELUAR=0
END REPEAT;
END;
$$
DELIMITER ;